Fix CVE issues
opensearch-project/alerting pull request #266
Opened 2021-12-31 00:07 UTC by lezzago

Signed-off-by: Ashish Agrawal <ashisagr@amazon.com>

*Issue #, if available:*
N/A
*Description of changes:*
Update dependencies to resolve CVEs

*CheckList:*
[X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-12-31 15:27 UTC, dblock requested changes
The force dependency seems wrong. Looks like you're inheriting a certain version from an upstream project like OpenSearch, these need to be fixed there.

2022-01-03 16:11 UTC, lezzago commented
> The force dependency seems wrong. Looks like you're inheriting a certain version from an upstream project like OpenSearch, these need to be fixed there.

Will update the dependencies in OpenSearch and will remove all the force dependencies in this PR

2022-01-03 17:06 UTC, dblock approved these changes

2022-01-03 17:26 UTC, skkosuri-amzn approved these changes

2022-01-03 19:49 UTC, merged

2022-01-03 20:29 UTC, dblock commented
Can we backport this one onto the 1.2 branch? We're likely to do a 1.2.4 release.