Ack alerts - allow moving alerts to history index with custom datasources
opensearch-project/alerting pull request #626
Opened 2022-10-27 18:32 UTC by petardz

Signed-off-by: Petar Dzepina <petar.dzepina@gmail.com>

*Issue #, if available:*

*Description of changes:*
Ack alerts - allow moving alerts to history index with custom datasources

*CheckList:*
[ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-27 20:13 UTC, eirsep commented
let's verify in integ test after acknowledging alert that we are moving the alerts to history index

2022-10-27 20:13 UTC, eirsep requested changes
plz add transport layer test

2022-10-28 00:22 UTC, eirsep approved these changes

2022-10-28 00:23 UTC, sbcd90 approved these changes

2022-10-28 00:24 UTC, merged